### ISSUE TITLE
`make release` throws error when copying to aws

### ISSUE THREAD

**Issue by additiverich** [shift72/kibble#114]
As per .goreleaser.yml, for each target `post: sh ./deploy_aws.sh {{.Version}} {{.Os}}` is executed but on my machine (OS X) the template `.Os` doesn't match a key entry

```
⨯ release failed after 9.71s error=post hook failed: template: tmpl:1:34: executing "tmpl" at <.Os>: map has no entry for key "Os"
```

I've hard-coded this to 'linux' for now but it deploys 3x at the moment

**Comment by stajs** [comment]
First guess would be an old version of goreleaser that doesn't have the field - `.Os` is in [latest docs for build-hooks](https://goreleaser.com/customization/build/#build-hooks).

My version is `1.6.3` but looks like `1.7.0` dropped two days ago.

I've added a branch if @additiverich and @l0ud0gg (the only Delivery Guy with a Mac) can both check it out and see what results you get when you run `kibble/goreleaser-os.sh`.

# Set up

In order to safely test the build-hook, I've invalidated the github token for the script:

![image](https://user-images.githubusercontent.com/2253814/159619381-dc1e814e-46e0-4a58-8df1-6f06fc428a7a.png)

... and nerfed the S3 upload in `kibble/deploy_aws.sh`:

![image](https://user-images.githubusercontent.com/2253814/159619290-0e41bd3d-c48e-4d79-b3d5-8df0edc993b8.png)

... and double surety in `kibble/.goreleaser.yml`:

![image](https://user-images.githubusercontent.com/2253814/159621357-d0b4c110-c047-4a87-a4c6-2f32f1bb815c.png)

I've then reinstated the `.Os`:

![image](https://user-images.githubusercontent.com/2253814/159619670-ccff70ec-e843-469f-9493-f5cc2448400b.png)

The rest of the script gathers the goreleaser version and runs a "release" (not really) with two additional flags:

![image](https://user-images.githubusercontent.com/2253814/159620075-77ef5c26-d228-47af-b309-63b8bef9ea98.png)

# Non-debug

Running with debug flag produces a lot of noise, so first remove it to get an easier view. For me it shows the OS being passed to each hook (window/darwin/linux):

![image](https://user-images.githubusercontent.com/2253814/159619982-b078549b-2837-4e78-8685-3156d49b4349.png)

# Debug

Add the debug flag back to see output from the hook script. It's messy but tracking down the lines:

```
running hook              hook=sh ./deploy_aws.sh 0.16.6 linux
We gots this OS: linux
fake uploading linux only version - 0.16.6
...
running hook              hook=sh ./deploy_aws.sh 0.16.6 windows
We gots this OS: windows
Skipping hook for windows
...
running hook              hook=sh ./deploy_aws.sh 0.16.6 darwin
We gots this OS: darwin
Skipping hook for darwin
```

And if you search for `GOOS` you can see the build command prior to the hook setting the OS, e.g.:

```
running                   cmd=[go build -ldflags=-s -w -X kibble/version.Version=0.16.6 ... LOTS OF JUNK ... GOOS=windows ... MORE JUNK]
```

**Comment by additiverich** [comment]
On the face of it appears to be passing in ok

> We gots this OS: linux
> ...
> We gots this OS: windows
> ...
> We gots this OS: darwin

**Comment by stajs** [comment]
Wait, what? So original run of goreleaser didn't have the OS parameter and now it does? What's changed? Did you upgrade goreleaser?

You obviously hit it at some stage but now I'm of the mind to close this as "can't repro".

Referencing #103 and #104.

For some more datapoints, from @PeculiarGoat running Ubuntu:

```
goreleaser version 1.6.3

running hook              hook=sh ./deploy_aws.sh 0.16.6 darwin
We gots this OS: darwin
Skipping hook for darwin

running hook              hook=sh ./deploy_aws.sh 0.16.6 linux
We gots this OS: linux
fake uploading linux only version - 0.16.6

running hook              hook=sh ./deploy_aws.sh 0.16.6 windows
We gots this OS: windows
Skipping hook for windows
```

... and @l0ud0gg running macOS:

> goreleaser version 1.7.0
> I got the same as PeculiarGoats output above. skipped darwin and windows, fake upload linux only version 0.16.6
